#!/bin/bash

set -e

case $1 in
    install|upgrade)
		INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
		if [ "systemd" == "${INITSYS}" ]; then
			service rustdesk stop || true
      sleep 1
      rm -rf /usr/bin/libsciter-gtk.so
		fi
        ;;
esac

# Remove legacy RustDesk desktop/icon entries. MDesk installs only mdesk.* launchers/icons.
rm -f /usr/share/applications/rustdesk.desktop /usr/share/applications/rustdesk-link.desktop || true
rm -f /usr/share/icons/hicolor/256x256/apps/rustdesk.png /usr/share/icons/hicolor/scalable/apps/rustdesk.svg || true

exit 0
